
name: Docker Release

on:
  release:
    types: [published]

env:
  DOCKER_USER: samueltallet
  DOCKER_REPO: mongodb-php-gui

jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: qemu setup
      uses: docker/setup-qemu-action@v2

    - name: docker buildx
      uses: docker/setup-buildx-action@v2
      with:
        config-inline: |
          [worker.oci]
            max-parallelism = 2

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: ${{ env.DOCKER_USER }}/${{ env.DOCKER_REPO }}:latest
